# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  database: daytripper_development
  username: root
  password:
  host: localhost
  encoding: utf8

test:
  adapter: mysql2
  database: daytripper_test
  username: root
  password:
  host: localhost
  encoding: utf8

production:
  adapter: mysql2
  database: daytripper_production
  username: root
  password:
  host: localhost
  encoding: utf8
